### ISSUE TITLE
💡 [FEATURE]: Implement Automated Release Notes Generation and Semantic Versioning

### ISSUE THREAD

**Issue by mihir-bombay-studio** [dear-digital/shopify-theme-skeleton#228]
### Duplicate check

- [X] I have searched the existing issues

### Feature Description

The goal of this issue is to establish an automated process for creating release notes and tagging, similar to how Shopify's Dawn repository manages its releases (e.g., [Dawn v12.0.0](https://github.com/Shopify/dawn/releases/tag/v12.0.0)). The process should automatically integrate issues into a changelog file. 

To achieve this, we need to research and possibly integrate tools and methodologies from the following resources:
1. GitHub's guide on [automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).
2. The [GitHub Changelog Generator](https://github.com/github-changelog-generator/github-changelog-generator) tool.

Additionally, the releases should adhere to [Semantic Versioning](https://semver.org/) principles. This ensures clarity and consistency in version numbering, especially for users and contributors who depend on versioning for integration and updates.

#### Motivation
Automating the release process and adhering to Semantic Versioning standards will streamline our deployment pipeline, reduce manual errors, and provide clear, standardized communication to users about changes and updates in each release. This system will save time and resources, ensuring a more efficient release process.

#### Additional Context
- Review existing release process to identify manual steps that can be automated.
- Ensure the solution is compatible with our current GitHub workflow and repository structure.
- The team should be briefed on Semantic Versioning principles to maintain consistency in versioning post-implementation.

### Information Completeness

- [X] Yes, I have provided all the necessary information

**Comment by kmalap05** [comment]
**I attempted to set up the process, but I'm struggling with configuring the generation of release notes. Could you provide some guidance or suggestions on how to achieve this?**

**File:** `.github/workflows/release.yml`
```
name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Specify the Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**File** `package.json`
```
{
  "name": "shopify-theme",
  "version": "1.0.0",
  "devDependencies": {
    "@semantic-release/changelog": "^6.0.3",
    "@semantic-release/commit-analyzer": "^11.1.0",
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/npm": "^11.0.2",
    "@semantic-release/release-notes-generator": "^12.1.0",
    "semantic-release": "^22.0.12",
    "tailwindcss": "^3.3.5"
  },
  "release": {
    "plugins": [
     "@semantic-release/commit-analyzer",
     "@semantic-release/release-notes-generator",
     ["@semantic-release/npm",{"npmPublish":false}],
     "@semantic-release/changelog",
     "@semantic-release/git"
   ],
   "branches": ["main"]
 }
}
```
